server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #lb表示启用负载均衡功能
          #          filters:
          #            -AddRequestParameter=X-Request-Id,1024 #过滤工厂会在匹配的请求头上加上一对请求头名称为X-Request-Id 值为1024
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            #- After=2021-03-16T15:42:50.058+08:00[Asia/Shanghai]
            #- Header=X-Request-Id, \d+
eureka:
  instance:
    hostname: cloud-gateway-service #访问隐藏ip 显示 http://cloud-gateway-service:9527/actuator/info
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


